CREATE TABLE `student` (
  `student_id` int(10) NOT NULL AUTO_INCREMENT,
  `ime` varchar (100) NOT NULL,
  `prezime` varchar(100) NOT NULL,
  `datum_rodjenja` varchar(100) NOT NULL,
  `JMBG` varchar(255) NOT NULL,
  `broj_telefona` varchar(255) NOT NULL,
  `grad_opstina` varchar(255) NOT NULL,
  `postanski_broj` varchar(100) NOT NULL,
  `region` varchar(100) NOT NULL,
  `ulica` varchar(100) NOT NULL,
  `broj_kuce` varchar(100) NOT NULL,
  `ime_oca` varchar(100) NOT NULL,
  `zanimanje_oca` varchar(100) NOT NULL,
  `ime_majke` varchar(100) NOT NULL,
  `zanimanje_majke` varchar(100) NOT NULL,
  `devojacko_prezime` varchar(100) NOT NULL,
  `naziv_skole` varchar(100) NOT NULL,
  `smer` varchar(100) NOT NULL,
  `godina_upisa` varchar(100) NOT NULL,
  `trajanje` varchar(100) NOT NULL,
  `grad_skole` varchar(100) NOT NULL,
  `pol` varchar(100) NOT NULL,
  `radno_stanje_oca` varchar(100) NOT NULL,
  `radno_stanje_majke` varchar(100) NOT NULL,
  `bracno_stanje` varchar(100) NOT NULL,
  `Vrsta_s` varchar(100) NOT NULL,
  `slika` varchar(100) NOT NULL,
  PRIMARY KEY(student_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;